// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using secured.pay.api.Context;

namespace secured.pay.api.Migrations
{
    [DbContext(typeof(DB_Sec_Pay))]
    [Migration("20200628101652_pay")]
    partial class pay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("secured.pay.api.Models.C_Transaction", b =>
                {
                    b.Property<long>("C_TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("CustomerCode");

                    b.Property<string>("Email");

                    b.Property<string>("MobileNo");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("OrderID");

                    b.Property<string>("PayeeName");

                    b.Property<string>("PaymentID");

                    b.Property<long>("PaymentStatusID");

                    b.Property<long>("PaymentTypeID");

                    b.Property<string>("ProductCode");

                    b.Property<string>("Signature");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<long?>("TransactionStepID");

                    b.HasKey("C_TransactionID");

                    b.HasIndex("PaymentStatusID");

                    b.HasIndex("PaymentTypeID");

                    b.HasIndex("TransactionStepID");

                    b.ToTable("C_Transactions");
                });

            modelBuilder.Entity("secured.pay.api.Models.PaymentStatus", b =>
                {
                    b.Property<long>("PaymentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("PaymentStatusID");

                    b.ToTable("PaymentStatuss");
                });

            modelBuilder.Entity("secured.pay.api.Models.PaymentType", b =>
                {
                    b.Property<long>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("PaymentTypeID");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("secured.pay.api.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("secured.pay.api.Models.RazorPay_Attribute", b =>
                {
                    b.Property<long>("RazorPay_AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("amount");

                    b.Property<string>("amount_due");

                    b.Property<string>("amount_paid");

                    b.Property<string>("attempts");

                    b.Property<string>("checkout_config_id");

                    b.Property<string>("created_at");

                    b.Property<string>("currency");

                    b.Property<string>("entity");

                    b.Property<string>("id");

                    b.Property<string>("offer_id");

                    b.Property<string>("receipt");

                    b.Property<string>("status");

                    b.HasKey("RazorPay_AttributeID");

                    b.ToTable("RazorPay_Attributes");
                });

            modelBuilder.Entity("secured.pay.api.Models.Razorpay_Config", b =>
                {
                    b.Property<long>("Razorpay_ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Enviorment");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Razorpay_ConfigID");

                    b.ToTable("Razorpay_Configs");
                });

            modelBuilder.Entity("secured.pay.api.Models.Step", b =>
                {
                    b.Property<long>("StepID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("StepID");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("secured.pay.api.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("CustomerCode");

                    b.Property<string>("Email");

                    b.Property<string>("MobileNo");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("OrderID");

                    b.Property<string>("PayeeName");

                    b.Property<string>("PaymentID");

                    b.Property<long>("PaymentStatusID");

                    b.Property<long>("PaymentTypeID");

                    b.Property<string>("ProductCode");

                    b.Property<string>("Signature");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<long?>("TransactionStepID");

                    b.HasKey("TransactionID");

                    b.HasIndex("PaymentStatusID");

                    b.HasIndex("PaymentTypeID");

                    b.HasIndex("TransactionStepID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("secured.pay.api.Models.TransactionStep", b =>
                {
                    b.Property<long>("TransactionStepID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("ApplicationUrl");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("CustomerCode");

                    b.Property<string>("Email");

                    b.Property<string>("ErrorUrl");

                    b.Property<string>("InvoiceNumber");

                    b.Property<string>("MobileNo");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PayeeName");

                    b.Property<string>("ProductCode");

                    b.Property<long>("RazorPay_AttributeID");

                    b.Property<long>("StepID");

                    b.Property<string>("SucessUrl");

                    b.Property<string>("SuscriptionNumber");

                    b.HasKey("TransactionStepID");

                    b.HasIndex("RazorPay_AttributeID");

                    b.HasIndex("StepID");

                    b.ToTable("TransactionSteps");
                });

            modelBuilder.Entity("secured.pay.api.Models.C_Transaction", b =>
                {
                    b.HasOne("secured.pay.api.Models.PaymentStatus", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("secured.pay.api.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("secured.pay.api.Models.TransactionStep", "TransactionStep")
                        .WithMany()
                        .HasForeignKey("TransactionStepID");
                });

            modelBuilder.Entity("secured.pay.api.Models.Transaction", b =>
                {
                    b.HasOne("secured.pay.api.Models.PaymentStatus", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("secured.pay.api.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("secured.pay.api.Models.TransactionStep", "TransactionStep")
                        .WithMany()
                        .HasForeignKey("TransactionStepID");
                });

            modelBuilder.Entity("secured.pay.api.Models.TransactionStep", b =>
                {
                    b.HasOne("secured.pay.api.Models.RazorPay_Attribute", "RazorPay_Attribute")
                        .WithMany()
                        .HasForeignKey("RazorPay_AttributeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("secured.pay.api.Models.Step", "Step")
                        .WithMany()
                        .HasForeignKey("StepID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
